apiVersion: v1
kind: Service
metadata:
  name: {{ include "zuzuflow.frontendServiceName" . }}
  labels:
    {{- include "zuzuflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "zuzuflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
